### ISSUE TITLE
graphics crash

### ISSUE THREAD

**Issue by Dylanstreamersx** [acc0untz0138/DenpaEx#6]
when I activated low quality and pressed graphics again, the game crashed
<img width="1441" alt="2024-05-11 (4)" src="https://github.com/acc0untz0138/DenpaEx/assets/116863282/db89e976-574f-488d-b7e7-50d2e4fc5c17">

**Comment by acc0untz0138** [comment]
ye i seen that error cuz it happened to me too lmao, ill try to fix it as soon as possible (may take 2 days cuz im not near my pc atm)
