### ISSUE TITLE
Error in stage

### ISSUE THREAD

**Issue by DxrkPxwer** [acc0untz0138/DenpaEx#7]
Yea, so i've decided to test this engine and created a lua stage, however the image isn't loading

**Comment by acc0untz0138** [comment]
i need more information. can you provide it? you sure you put the image directory correctly?

**Comment by acc0untz0138** [comment]
also fyi; stage lua goes in mods/scripts/stages, and stage json goes in mods/data/stages. yes thats 2 different locations, but thats how it works in denpaex

**Comment by DxrkPxwer** [comment]
Oh ok

> Owner

by the way the fact that this is very organized confuses me, so i was already expecting this would happen lo l

**Comment by DxrkPxwer** [comment]
thats the reason why it's not working haha im a dummy
